import type { Question } from "../types";

/**
 * Track C — 부모·가족을 대신해 준비
 * 진단이 먼저다. 설계는 그다음이다. 14문항.
 */
export const caregiverQuestions: Question[] = [
  /* ── C-1 대상자 진단 ───────────────────────────── */
  {
    id: "C01",
    track: "caregiver",
    section: "대상자 파악",
    prompt: "누구를 대신해 알아보고 계신가요?",
    helper: "관계에 따라 후견 심판을 청구할 수 있는 자격과 순위가 달라져요.",
    type: "choice",
    options: [
      { value: "parent", label: "부모님" },
      { value: "spouse", label: "배우자" },
      { value: "grandparent", label: "조부모" },
      { value: "sibling", label: "형제자매" },
      { value: "other", label: "그 외 친족" },
    ],
    mapsTo: [{ doc: "guardianship", clause: "제1조", label: "청구권자 적격" }],
  },
  {
    id: "C02",
    track: "caregiver",
    section: "대상자 파악",
    prompt: "최근 그분에게서 어떤 변화가 보이나요?",
    helper: "해당하는 것을 모두 골라 주세요. 어느 제도를 쓸 수 있는지 판단하는 가장 중요한 근거예요.",
    type: "multi",
    options: [
      { value: "repeat", label: "같은 말이나 질문을 반복하세요" },
      { value: "unpaid", label: "공과금이나 카드값이 밀린 적이 있어요" },
      { value: "odd_transfer", label: "설명되지 않는 이체나 인출이 있었어요" },
      { value: "lost_card", label: "카드나 통장을 자주 잃어버리세요" },
      { value: "diagnosed", label: "치매나 인지장애 진단을 받으셨어요" },
      { value: "hospital", label: "입원 중이거나 요양시설에 계세요" },
      { value: "none", label: "특별한 변화는 아직 없어요" },
    ],
    mapsTo: [{ doc: "guardianship", clause: "제1조", label: "의사능력 판단 근거" }],
  },
  {
    id: "C03",
    track: "caregiver",
    section: "대상자 파악",
    prompt: "그분이 지금 서류의 내용을 이해하고 스스로 서명하실 수 있나요?",
    helper:
      "임의후견계약과 신탁계약은 본인이 스스로 결정할 수 있어야 맺을 수 있어요. 이 답이 쓸 수 있는 제도를 정해요.",
    type: "choice",
    options: [
      { value: "yes", label: "네, 충분히 이해하고 서명하실 수 있어요" },
      { value: "partial", label: "쉬운 내용은 되지만 복잡한 것은 어려워요" },
      {
        value: "no",
        label: "아니요, 어려워요",
        warn: "본인이 스스로 결정하기 어려우면 새로 신탁이나 임의후견계약을 맺기 어려워요. 법정후견 절차를 중심으로 설계해요.",
      },
      { value: "unknown", label: "잘 모르겠어요" },
    ],
    mapsTo: [{ doc: "guardianship", clause: "제1조", label: "제도 판정" }],
  },
  {
    id: "C04",
    track: "caregiver",
    section: "대상자 파악",
    prompt: "지금 가장 급한 문제는 무엇인가요?",
    helper: "급한 문제가 있으면 설계보다 먼저 할 일을 앞에 둬요.",
    type: "multi",
    options: [
      { value: "hospital_bill", label: "병원비를 낼 방법이 없어요" },
      { value: "account", label: "통장을 쓸 수 없어요" },
      { value: "overdue", label: "공과금이 밀리고 있어요" },
      { value: "estate", label: "부동산을 팔아야 하는데 못 하고 있어요" },
      { value: "fraud", label: "사기 피해를 당하셨거나 의심돼요" },
      { value: "none", label: "아직 급한 것은 없어요" },
    ],
    mapsTo: [
      { doc: "guardianship", clause: "제5조", label: "긴급 조치" },
      { doc: "expense", clause: "제4조", label: "즉시 차단 항목" },
    ],
  },

  /* ── C-2 가족 관계 ─────────────────────────────── */
  {
    id: "C05",
    track: "caregiver",
    section: "가족 관계",
    prompt: "그분의 자녀나 배우자 등 다른 가족은 모두 몇 분인가요?",
    helper: "후견 심판에서는 다른 가족의 의견도 확인해요. 본인을 포함한 숫자로 적어 주세요.",
    type: "amount",
    min: 1,
    max: 12,
    step: 1,
    unit: "명",
    presets: [1, 2, 3, 4],
    mapsTo: [{ doc: "guardianship", clause: "제5조", label: "이해관계인" }],
  },
  {
    id: "C06",
    track: "caregiver",
    section: "가족 관계",
    prompt: "가족들 사이에 의견이 모였나요?",
    helper: "가족 갈등은 후견 절차가 길어지는 가장 큰 원인이에요. 감정 절차가 더해지기도 해요.",
    type: "choice",
    options: [
      { value: "agreed", label: "모두 동의했어요" },
      { value: "partial", label: "대체로 동의하지만 일부 다른 의견이 있어요" },
      { value: "notyet", label: "아직 이야기를 꺼내지 못했어요" },
      {
        value: "conflict",
        label: "갈등이 있어요",
        warn: "가족끼리 다툼이 있으면 법원이 가족 대신 전문가 후견인을 정하는 경우가 있어요.",
      },
    ],
    mapsTo: [{ doc: "guardianship", clause: "제5조", label: "절차 리스크" }],
  },
  {
    id: "C07",
    track: "caregiver",
    section: "가족 관계",
    prompt: "후견인이 된다면 누가 하시겠어요?",
    helper: "본인일 수도, 다른 가족일 수도, 전문가일 수도 있어요.",
    type: "person",
    mapsTo: [{ doc: "guardianship", clause: "제2조", label: "후견인 후보" }],
  },
  {
    id: "C12",
    track: "caregiver",
    section: "가족 관계",
    prompt: "그분 본인은 이 준비를 알고 계신가요?",
    helper: "본인이 알고 동의하면 절차가 훨씬 수월해요. 임의후견이라는 선택지도 열려요.",
    type: "choice",
    options: [
      { value: "yes_agree", label: "알고 계시고 동의하셨어요" },
      { value: "yes_reluctant", label: "알고 계시지만 내켜하지 않으세요" },
      { value: "no", label: "아직 말씀드리지 않았어요" },
      { value: "cannot", label: "말씀드려도 이해하기 어려운 상태예요" },
    ],
    mapsTo: [{ doc: "guardianship", clause: "제1조", label: "본인 동의" }],
  },

  /* ── C-3 재산과 지출 ───────────────────────────── */
  {
    id: "C08",
    track: "caregiver",
    section: "재산과 지출",
    prompt: "그분의 자산은 어떻게 되나요?",
    helper: "아는 범위에서 대략 적어 주세요. 후견이 시작되면 법원에 재산 목록을 내게 돼요.",
    type: "multi",
    withAmount: true,
    options: [
      { value: "deposit", label: "예금·적금" },
      { value: "invest", label: "주식·펀드" },
      { value: "realestate", label: "부동산" },
      { value: "pension", label: "연금" },
      { value: "insurance", label: "보험" },
      { value: "unknown", label: "잘 모르겠어요" },
    ],
    mapsTo: [
      { doc: "guardianship", clause: "제5조", label: "재산목록" },
      { doc: "expense", clause: "제6조", label: "지속가능성" },
    ],
  },
  {
    id: "C09",
    track: "caregiver",
    section: "재산과 지출",
    prompt: "그분에게 매달 나가는 고정지출은 무엇인가요?",
    helper: "후견인이 되면 이 지출을 대신 관리하게 돼요. 자동이체 목록이 돼요.",
    type: "multi",
    withAmount: true,
    options: [
      { value: "utility", label: "전기·가스·수도·관리비" },
      { value: "telecom", label: "통신비" },
      { value: "insurance", label: "보험료" },
      { value: "care", label: "요양·간병비" },
      { value: "hospital", label: "병원 정기 치료비" },
      { value: "rent", label: "월세·대출 이자" },
    ],
    mapsTo: [{ doc: "expense", clause: "제2조", label: "자동이체 매트릭스" }],
  },
  {
    id: "C10",
    track: "caregiver",
    section: "재산과 지출",
    prompt: "그분의 월 수입은 얼마인가요?",
    helper: "국민연금, 기초연금, 임대소득 등을 모두 합해 주세요.",
    type: "amount",
    min: 0,
    max: 10_000_000,
    step: 100_000,
    presets: [400_000, 700_000, 1_500_000, 2_500_000],
    mapsTo: [{ doc: "expense", clause: "제6조", label: "월 수입" }],
  },

  /* ── C-4 준비 상태 ─────────────────────────────── */
  {
    id: "C11",
    track: "caregiver",
    section: "준비 상태",
    prompt: "지금 가지고 계신 서류가 있나요?",
    helper: "없는 서류는 준비할 것으로 표시해 드려요.",
    type: "multi",
    options: [
      { value: "family", label: "가족관계증명서" },
      { value: "diagnosis", label: "진단서 또는 소견서" },
      { value: "bankbook", label: "통장·거래내역" },
      { value: "registry", label: "부동산 등기부등본" },
      { value: "resident", label: "주민등록등본" },
      { value: "none", label: "아직 없어요" },
    ],
    mapsTo: [{ doc: "guardianship", clause: "제5조", label: "구비서류" }],
  },
  {
    id: "C13",
    track: "caregiver",
    section: "준비 상태",
    prompt: "어떤 일까지 대신할 수 있어야 하나요?",
    helper: "여기서 고른 항목이 후견 심판에서 청구할 일의 범위가 돼요.",
    type: "multi",
    options: [
      { value: "deposit_use", label: "예금 입출금" },
      { value: "deposit_break", label: "정기예금 해지" },
      { value: "estate_sell", label: "부동산 처분" },
      { value: "estate_rent", label: "부동산 임대 관리" },
      { value: "tax", label: "세금·공과금 납부" },
      { value: "insurance", label: "보험 청구·해지" },
      { value: "medical", label: "의료행위 동의" },
      { value: "facility", label: "요양시설 계약" },
    ],
    mapsTo: [{ doc: "guardianship", clause: "제3조", label: "사무범위" }],
  },
  {
    id: "C14",
    track: "caregiver",
    section: "준비 상태",
    prompt: "지금 가장 걱정되는 것은 무엇인가요?",
    helper: "편하게 적어 주세요. 설계서에 먼저 살펴볼 일로 들어가요.",
    type: "open",
    optional: true,
    placeholder: "예: 형이 아버지 통장을 혼자 관리하는 게 불안해요.",
    mapsTo: [{ doc: "guardianship", clause: "제5조", label: "우선 검토사항" }],
  },
];
