import type { Question } from "../types";

/**
 * Track A — 일상 지출·공과금 관리
 * 신탁·후견을 한 번도 언급하지 않는다. 8문항 / 약 2분.
 */
export const dailyQuestions: Question[] = [
  {
    id: "A01",
    track: "daily",
    section: "고정지출",
    prompt: "매달 반드시 빠져나가야 하는 돈은 무엇인가요?",
    helper: "여기서 고른 항목이 자동이체 매트릭스의 각 행이 됩니다. 금액은 대략이어도 괜찮아요.",
    type: "multi",
    withAmount: true,
    options: [
      { value: "utility", label: "전기·가스·수도" },
      { value: "maintenance", label: "아파트 관리비" },
      { value: "telecom", label: "통신비 (휴대폰·인터넷)" },
      { value: "insurance", label: "보험료" },
      { value: "rent", label: "월세 또는 대출 이자" },
      { value: "subscription", label: "정기 구독 서비스" },
      { value: "care", label: "요양·간병 비용" },
      { value: "support", label: "가족 정기 지원" },
    ],
    mapsTo: [{ doc: "expense", clause: "§2", label: "자동이체 매트릭스" }],
  },
  {
    id: "A02",
    track: "daily",
    section: "고정지출",
    prompt: "고정지출 말고, 생활비는 매달 얼마면 충분할까요?",
    helper: "식비·교통비·병원 통원 등 손에 쥐고 쓰는 돈입니다. 생활계좌의 월 유입액이 됩니다.",
    type: "amount",
    min: 300_000,
    max: 8_000_000,
    step: 100_000,
    presets: [1_000_000, 1_500_000, 2_000_000, 3_000_000],
    mapsTo: [{ doc: "expense", clause: "§1", label: "생활계좌 유입액" }],
  },
  {
    id: "A03",
    track: "daily",
    section: "지급 방식",
    prompt: "생활비를 어떤 주기로 받고 싶으세요?",
    helper: "한 번에 많이 받으면 편하지만, 나눠 받으면 사기 피해 규모가 줄어듭니다.",
    type: "choice",
    options: [
      { value: "monthly", label: "매달 1일에 한 번", hint: "가장 일반적" },
      { value: "biweekly", label: "2주에 한 번" },
      { value: "weekly", label: "매주", hint: "피해 규모 최소화" },
      { value: "ondemand", label: "필요할 때 청구해서" },
    ],
    mapsTo: [{ doc: "expense", clause: "§1", label: "지급 주기" }],
  },
  {
    id: "A04",
    track: "daily",
    section: "지급 방식",
    prompt: "자동이체가 잔액 부족으로 실패하면 어떻게 할까요?",
    helper: "연체는 신용도와 공과금 할증으로 이어집니다. 실패 시 조치를 미리 정해두는 항목입니다.",
    type: "choice",
    options: [
      { value: "auto_cover", label: "예비계좌에서 자동으로 채워 결제", hint: "권장" },
      { value: "notify_only", label: "나에게 알림만 보내기" },
      { value: "notify_guardian", label: "지정한 사람에게도 함께 알리기" },
      { value: "hold", label: "결제를 보류하고 승인 요청" },
    ],
    mapsTo: [{ doc: "expense", clause: "§2", label: "이체 실패 시 조치" }],
  },
  {
    id: "A05",
    track: "daily",
    section: "한도와 차단",
    prompt: "한 번에 이체할 수 있는 최대 금액을 얼마로 할까요?",
    helper: "이 금액을 넘는 이체는 보류되고 확인 절차를 거칩니다. 보이스피싱 피해의 상한선입니다.",
    type: "amount",
    min: 100_000,
    max: 30_000_000,
    step: 100_000,
    presets: [500_000, 1_000_000, 3_000_000, 5_000_000],
    mapsTo: [{ doc: "expense", clause: "§3", label: "1회 이체 한도" }],
  },
  {
    id: "A06",
    track: "daily",
    section: "한도와 차단",
    prompt: "어떤 거래를 수상하게 보고 막을까요?",
    helper: "고른 항목만 이상거래 룰셋에서 활성화됩니다. 고르지 않은 것은 회색으로 남습니다.",
    type: "multi",
    options: [
      { value: "new_payee", label: "처음 보는 계좌로 큰 금액 보내기" },
      { value: "night", label: "밤 11시~새벽 6시 사이 고액 이체" },
      { value: "loan", label: "대출·카드 현금서비스 실행" },
      { value: "remote", label: "원격제어 앱이 켜진 상태의 이체" },
      { value: "overseas", label: "해외 송금" },
      { value: "deposit_break", label: "정기예금 중도해지" },
    ],
    mapsTo: [{ doc: "expense", clause: "§4", label: "이상거래 룰셋" }],
  },
  {
    id: "A07",
    track: "daily",
    section: "알림",
    prompt: "이상 상황이 생기면 누구에게 알릴까요?",
    helper: "본인 외 최소 1명을 두는 것을 권합니다. 본인이 판단하기 어려운 상황이 바로 위험한 상황이기 때문입니다.",
    type: "person",
    mapsTo: [{ doc: "expense", clause: "§5", label: "알림 대상" }],
  },
  {
    id: "A08",
    track: "daily",
    section: "알림",
    prompt: "병원비처럼 갑작스러운 큰 지출은 어떻게 처리할까요?",
    helper: "막기만 하면 정작 필요할 때 돈이 안 나갑니다. 예외 경로를 함께 설계합니다.",
    type: "choice",
    options: [
      { value: "auto_within", label: "정해둔 한도 안에서는 자동으로 집행" },
      { value: "approve", label: "지정한 사람의 승인을 받고 집행", hint: "권장" },
      { value: "notify_after", label: "먼저 집행하고 바로 통보" },
      { value: "reserve", label: "의료예비계좌를 따로 만들어 거기서 집행" },
    ],
    mapsTo: [
      { doc: "expense", clause: "§1", label: "의료예비계좌" },
      { doc: "expense", clause: "§5", label: "예외 승인 경로" },
    ],
  },
];
