import type { Question } from "../types";

/**
 * 상속 챕터 (선택) — 옛 Track D 를 그대로 이관했다.
 * 유언대용신탁·수익자연속신탁 중심. 16문항. 질문 ID(D*)와 mapsTo 는 불변이다.
 */
export const estateQuestions: Question[] = [
  /* ── D-1 상속인과 재산 ─────────────────────────── */
  {
    id: "D01",
    track: "estate",
    chapter: "estate",
    section: "상속인과 재산",
    prompt: "상속을 받게 될 분들은 누구인가요?",
    helper: "인원까지 적어 주시면 법정상속분과 유류분을 함께 계산해 드려요.",
    type: "multi",
    withAmount: true,
    options: [
      { value: "spouse", label: "배우자", hint: "인원 칸에 1" },
      { value: "child", label: "자녀", hint: "인원 수만큼" },
      { value: "parent", label: "부모" },
      { value: "sibling", label: "형제자매" },
    ],
    mapsTo: [{ doc: "trust", clause: "제3조", label: "수익자 구성" }],
  },
  {
    id: "D02",
    track: "estate",
    chapter: "estate",
    section: "상속인과 재산",
    prompt: "남기실 재산은 어떤 것들인가요?",
    helper: "자산 종류에 따라 신탁에 넣을 수 있는지와 세금이 달라요.",
    type: "multi",
    withAmount: true,
    options: [
      { value: "deposit", label: "예금·적금" },
      { value: "invest", label: "주식·펀드·채권" },
      { value: "realestate", label: "부동산" },
      { value: "business", label: "사업체·지분" },
      { value: "insurance", label: "보험" },
    ],
    mapsTo: [{ doc: "trust", clause: "제2조", label: "신탁재산" }],
  },
  {
    id: "D03",
    track: "estate",
    chapter: "estate",
    section: "상속인과 재산",
    prompt: "특정 재산을 특정한 분에게 남기고 싶으세요?",
    helper: "여기서 정한 배분이 신탁설계서 제11조에 들어가요.",
    type: "allocation",
    mapsTo: [{ doc: "trust", clause: "제11조", label: "재산 배분" }],
  },

  /* ── D-2 구조 설계 ─────────────────────────────── */
  {
    id: "D04",
    track: "estate",
    chapter: "estate",
    section: "구조 설계",
    prompt: "배우자가 먼저 받고, 그다음 자녀에게 넘어가길 원하세요?",
    helper:
      "이렇게 하고 싶으시면 수익자연속신탁을 살펴봐요. 유언만으로는 그다음 받을 사람까지 정하기 어려워요.",
    type: "choice",
    options: [
      { value: "yes", label: "네, 배우자 먼저 그다음 자녀에게" },
      { value: "direct", label: "아니요, 처음부터 자녀에게" },
      { value: "split", label: "처음부터 나눠서 각각" },
      { value: "undecided", label: "아직 정하지 못했어요" },
    ],
    mapsTo: [{ doc: "trust", clause: "제3조", label: "수익자 연속" }],
  },
  {
    id: "D05",
    track: "estate",
    chapter: "estate",
    section: "구조 설계",
    prompt: "살아 있는 동안 미리 나눠 주고 싶으세요?",
    helper: "지금 주면 세금과 시점이, 나중에 넘기면 다툼 가능성이 각각 문제가 돼요.",
    type: "choice",
    options: [
      { value: "after", label: "전부 세상을 떠난 뒤에" },
      { value: "partial", label: "일부는 지금, 나머지는 떠난 뒤에" },
      { value: "now", label: "가능한 한 지금 나눠 주고 싶어요" },
    ],
    mapsTo: [{ doc: "trust", clause: "제5조", label: "이전 시점" }],
  },
  {
    id: "D06",
    track: "estate",
    chapter: "estate",
    section: "구조 설계",
    prompt: "유류분이라는 제도를 알고 계신가요?",
    helper:
      "한 사람에게 몰아주더라도 다른 상속인이 최소한의 몫을 달라고 할 수 있는 제도예요. 배분이 한쪽으로 쏠리면 미리 알려 드려요.",
    type: "choice",
    options: [
      { value: "know_ok", label: "알고 있고, 감안해서 나눌 생각이에요" },
      { value: "know_ignore", label: "알고 있지만 그래도 몰아주고 싶어요" },
      { value: "unknown", label: "처음 들어요" },
    ],
    mapsTo: [{ doc: "trust", clause: "제11조", label: "유류분 검토" }],
  },
  {
    id: "D07",
    track: "estate",
    chapter: "estate",
    section: "구조 설계",
    prompt: "상속인 중에 특별히 더 챙겨야 할 분이 있나요?",
    helper: "장애가 있거나 미성년이거나 투병 중인 상속인이 있으면 지급 방식부터 다르게 정해야 해요.",
    type: "choice",
    options: [
      { value: "disabled", label: "장애가 있는 자녀가 있어요" },
      { value: "minor", label: "미성년 자녀나 손주가 있어요" },
      { value: "ill", label: "투병 중인 가족이 있어요" },
      { value: "none", label: "특별히 없어요" },
    ],
    mapsTo: [{ doc: "trust", clause: "제5조", label: "특별 수익자 지급" }],
  },
  {
    id: "D08",
    track: "estate",
    chapter: "estate",
    section: "구조 설계",
    prompt: "사업체나 회사 지분을 갖고 계신가요?",
    helper: "지분을 나눠 물려주면 경영권이 흩어져요. 따로 정해야 하는 항목이에요.",
    type: "choice",
    options: [
      { value: "yes_succeed", label: "있고, 물려줄 사람이 정해져 있어요" },
      { value: "yes_undecided", label: "있지만 아직 정하지 못했어요" },
      { value: "no", label: "없어요" },
    ],
    mapsTo: [{ doc: "trust", clause: "제7조", label: "사업 지분 관리" }],
  },

  /* ── D-3 내 노후와 안전장치 ────────────────────── */
  {
    id: "D09",
    track: "estate",
    chapter: "estate",
    section: "내 노후",
    prompt: "그래도 내가 쓸 생활비는 매달 얼마가 필요할까요?",
    helper: "미리 나눠 주고 정작 내 노후 자금이 모자라는 경우가 적지 않아요.",
    type: "amount",
    min: 500_000,
    max: 10_000_000,
    step: 100_000,
    presets: [1_500_000, 2_000_000, 3_000_000],
    mapsTo: [
      { doc: "trust", clause: "제5조", label: "위탁자 생활비 유보" },
      { doc: "expense", clause: "제1조", label: "생활계좌" },
    ],
  },
  {
    id: "D10",
    track: "estate",
    chapter: "estate",
    section: "내 노후",
    prompt: "언제부터 실행하고 싶으세요?",
    helper: "시기에 따라 준비 순서가 달라져요.",
    type: "choice",
    options: [
      { value: "now", label: "가능한 한 빨리" },
      { value: "year", label: "1년 안에" },
      { value: "later", label: "천천히, 몇 년 안에" },
      { value: "research", label: "지금은 알아보는 중이에요" },
    ],
    mapsTo: [{ doc: "trust", clause: "제10조", label: "실행 시기" }],
  },
  {
    id: "D11",
    track: "estate",
    chapter: "estate",
    section: "내 노후",
    prompt: "재산 관리를 맡길 사람은 누구인가요?",
    helper: "살아 있을 때는 관리자, 떠난 뒤에는 집행자 역할을 함께 하는 경우가 많아요.",
    type: "person",
    mapsTo: [{ doc: "trust", clause: "제3조", label: "관리자" }],
  },
  {
    id: "D12",
    track: "estate",
    chapter: "estate",
    section: "내 노후",
    prompt: "내 뜻대로 되고 있는지 확인해 줄 사람은 누구인가요?",
    helper: "관리자와 다른 사람이어야 서로 견제가 돼요. 신탁감독인이 되는 사람이에요.",
    type: "person",
    mapsTo: [{ doc: "trust", clause: "제9조", label: "신탁감독인" }],
  },
  {
    id: "D13",
    track: "estate",
    chapter: "estate",
    section: "내 노후",
    prompt: "절대 팔거나 넘기면 안 되는 재산이 있나요?",
    helper: "신탁설계서 제8조에 하면 안 되는 일로 들어가요.",
    type: "multi",
    options: [
      { value: "home", label: "지금 살고 있는 집" },
      { value: "land", label: "선산·토지" },
      { value: "business", label: "사업체 지분" },
      { value: "memento", label: "특별한 의미가 있는 자산" },
      { value: "none", label: "특별히 없어요" },
    ],
    mapsTo: [{ doc: "trust", clause: "제8조", label: "처분 금지" }],
  },
  {
    id: "D14",
    track: "estate",
    chapter: "estate",
    section: "내 노후",
    prompt: "상속인들 사이에 다툼이 생길 것 같나요?",
    helper: "그럴 것 같으면 유언보다 신탁이 다툼을 막는 데 유리한 편이에요.",
    type: "choice",
    options: [
      { value: "likely", label: "네, 그럴 것 같아요" },
      { value: "maybe", label: "가능성은 있어요" },
      { value: "unlikely", label: "그렇지 않을 것 같아요" },
    ],
    mapsTo: [{ doc: "trust", clause: "제11조", label: "분쟁 방지 구조" }],
  },
  {
    id: "D15",
    track: "estate",
    chapter: "estate",
    section: "내 노후",
    prompt: "세금은 어떻게 생각하세요?",
    helper: "NEXT는 세금을 계산하지 않아요. 다만 어떤 항목을 세무 전문가와 확인해야 하는지 짚어 드려요.",
    type: "choice",
    options: [
      { value: "minimize", label: "가능한 한 줄이고 싶어요" },
      { value: "fair", label: "적당히 내더라도 다툼이 없는 게 우선이에요" },
      { value: "unknown", label: "잘 모르겠어요" },
    ],
    mapsTo: [{ doc: "trust", clause: "부속", label: "세무 검토 항목" }],
  },
  {
    id: "D16",
    track: "estate",
    chapter: "estate",
    section: "내 노후",
    prompt: "가족에게 남기고 싶은 말씀이 있나요?",
    helper: "설계서 맨 앞에 그대로 실려요.",
    type: "open",
    optional: true,
    placeholder: "예: 집은 어머니가 사시는 동안은 팔지 않았으면 합니다.",
    mapsTo: [{ doc: "trust", clause: "서문", label: "위탁자의 뜻" }],
  },
];
