import type { Question } from "../types";

/**
 * 상속 챕터 (선택) — 옛 Track D 를 그대로 이관했다.
 * 유언대용신탁·수익자연속신탁 중심. 16문항. 질문 ID(D*)와 mapsTo 는 불변이다.
 */
export const estateQuestions: Question[] = [
  /* ── D-1 상속인과 재산 ─────────────────────────── */
  {
    id: "D01",
    track: "estate",
    chapter: "estate",
    section: "상속인과 재산",
    prompt: "상속인이 될 분들은 어떻게 되나요?",
    helper: "인원까지 적어 주시면 법정상속분과 유류분을 함께 계산해 드립니다.",
    type: "multi",
    withAmount: true,
    options: [
      { value: "spouse", label: "배우자", hint: "인원 칸에 1" },
      { value: "child", label: "자녀", hint: "인원 수만큼" },
      { value: "parent", label: "부모" },
      { value: "sibling", label: "형제자매" },
    ],
    mapsTo: [{ doc: "trust", clause: "제3조", label: "수익자 구성" }],
  },
  {
    id: "D02",
    track: "estate",
    chapter: "estate",
    section: "상속인과 재산",
    prompt: "남기실 재산은 어떻게 되나요?",
    helper: "자산 종류에 따라 신탁 가능 여부와 세금 구조가 다릅니다.",
    type: "multi",
    withAmount: true,
    options: [
      { value: "deposit", label: "예금·적금" },
      { value: "invest", label: "주식·펀드·채권" },
      { value: "realestate", label: "부동산" },
      { value: "business", label: "사업체·지분" },
      { value: "insurance", label: "보험" },
    ],
    mapsTo: [{ doc: "trust", clause: "제2조", label: "신탁재산" }],
  },
  {
    id: "D03",
    track: "estate",
    chapter: "estate",
    section: "상속인과 재산",
    prompt: "특정 재산을 특정한 분에게 남기고 싶으세요?",
    helper: "여기서 정한 배분이 잔여재산 귀속 조항(제11조)이 됩니다.",
    type: "allocation",
    mapsTo: [{ doc: "trust", clause: "제11조", label: "재산 배분" }],
  },

  /* ── D-2 구조 설계 ─────────────────────────────── */
  {
    id: "D04",
    track: "estate",
    chapter: "estate",
    section: "구조 설계",
    prompt: "배우자가 먼저 받고, 그다음 자녀에게 넘어가길 원하세요?",
    helper:
      "이 구조를 원하시면 수익자연속신탁이 검토 대상이 됩니다. 유언만으로는 2차 수익자를 지정하기 어렵습니다.",
    type: "choice",
    options: [
      { value: "yes", label: "네, 배우자 먼저 그다음 자녀에게" },
      { value: "direct", label: "아니요, 처음부터 자녀에게" },
      { value: "split", label: "처음부터 나눠서 각각" },
      { value: "undecided", label: "아직 정하지 못했습니다" },
    ],
    mapsTo: [{ doc: "trust", clause: "제3조", label: "수익자 연속" }],
  },
  {
    id: "D05",
    track: "estate",
    chapter: "estate",
    section: "구조 설계",
    prompt: "살아 있는 동안 미리 나눠주고 싶으세요?",
    helper: "생전 증여는 세금과 시점이, 사후 이전은 분쟁 가능성이 각각 다른 변수입니다.",
    type: "choice",
    options: [
      { value: "after", label: "전부 사후에" },
      { value: "partial", label: "일부는 지금, 나머지는 사후에" },
      { value: "now", label: "가능한 한 지금 나눠주고 싶다" },
    ],
    mapsTo: [{ doc: "trust", clause: "제5조", label: "이전 시점" }],
  },
  {
    id: "D06",
    track: "estate",
    chapter: "estate",
    section: "구조 설계",
    prompt: "유류분에 대해 알고 계신가요?",
    helper:
      "특정인에게 몰아주더라도 다른 상속인이 최소한의 몫을 청구할 수 있는 제도입니다. 배분이 한쪽으로 쏠리면 경고를 표시합니다.",
    type: "choice",
    options: [
      { value: "know_ok", label: "알고 있고, 감안해서 나눌 생각입니다" },
      { value: "know_ignore", label: "알고 있지만 그래도 몰아주고 싶습니다" },
      { value: "unknown", label: "처음 듣습니다" },
    ],
    mapsTo: [{ doc: "trust", clause: "제11조", label: "유류분 검토" }],
  },
  {
    id: "D07",
    track: "estate",
    chapter: "estate",
    section: "구조 설계",
    prompt: "상속인 중 특별히 더 지원이 필요한 분이 계신가요?",
    helper: "장애·미성년·투병 중인 상속인이 있으면 지급 방식 자체를 다르게 설계해야 합니다.",
    type: "choice",
    options: [
      { value: "disabled", label: "장애가 있는 자녀가 있습니다" },
      { value: "minor", label: "미성년 자녀·손주가 있습니다" },
      { value: "ill", label: "투병 중인 가족이 있습니다" },
      { value: "none", label: "특별히 없습니다" },
    ],
    mapsTo: [{ doc: "trust", clause: "제5조", label: "특별 수익자 지급" }],
  },
  {
    id: "D08",
    track: "estate",
    chapter: "estate",
    section: "구조 설계",
    prompt: "사업체나 지분을 가지고 계신가요?",
    helper: "지분은 분할 상속 시 경영권이 흩어집니다. 별도 설계가 필요한 항목입니다.",
    type: "choice",
    options: [
      { value: "yes_succeed", label: "있고, 물려줄 사람이 정해져 있습니다" },
      { value: "yes_undecided", label: "있지만 아직 정하지 못했습니다" },
      { value: "no", label: "없습니다" },
    ],
    mapsTo: [{ doc: "trust", clause: "제7조", label: "사업 지분 관리" }],
  },

  /* ── D-3 내 노후와 안전장치 ────────────────────── */
  {
    id: "D09",
    track: "estate",
    chapter: "estate",
    section: "내 노후",
    prompt: "그래도 내가 쓸 생활비는 매달 얼마가 필요할까요?",
    helper: "미리 나눠주고 정작 본인 노후자금이 부족해지는 경우가 적지 않습니다.",
    type: "amount",
    min: 500_000,
    max: 10_000_000,
    step: 100_000,
    presets: [1_500_000, 2_000_000, 3_000_000],
    mapsTo: [
      { doc: "trust", clause: "제5조", label: "위탁자 생활비 유보" },
      { doc: "expense", clause: "제1조", label: "생활계좌" },
    ],
  },
  {
    id: "D10",
    track: "estate",
    chapter: "estate",
    section: "내 노후",
    prompt: "언제부터 실행하고 싶으세요?",
    helper: "실행 시기에 따라 로드맵의 단계가 달라집니다.",
    type: "choice",
    options: [
      { value: "now", label: "가능한 한 빨리" },
      { value: "year", label: "1년 안에" },
      { value: "later", label: "천천히, 몇 년 안에" },
      { value: "research", label: "지금은 알아보는 단계" },
    ],
    mapsTo: [{ doc: "trust", clause: "제10조", label: "실행 시기" }],
  },
  {
    id: "D11",
    track: "estate",
    chapter: "estate",
    section: "내 노후",
    prompt: "재산 관리를 맡길 사람은 누구인가요?",
    helper: "생전에는 관리자, 사후에는 집행자 역할을 겸하는 경우가 많습니다.",
    type: "person",
    mapsTo: [{ doc: "trust", clause: "제3조", label: "관리자" }],
  },
  {
    id: "D12",
    track: "estate",
    chapter: "estate",
    section: "내 노후",
    prompt: "내 뜻대로 집행되는지 확인해 줄 사람은 누구인가요?",
    helper: "관리자와 다른 사람이어야 견제가 됩니다. 신탁감독인에 해당합니다.",
    type: "person",
    mapsTo: [{ doc: "trust", clause: "제9조", label: "신탁감독인" }],
  },
  {
    id: "D13",
    track: "estate",
    chapter: "estate",
    section: "내 노후",
    prompt: "절대 처분하지 말아야 할 재산이 있나요?",
    helper: "금지행위 조항(제8조)이 됩니다.",
    type: "multi",
    options: [
      { value: "home", label: "현재 살고 있는 집" },
      { value: "land", label: "선산·토지" },
      { value: "business", label: "사업체 지분" },
      { value: "memento", label: "특별한 의미가 있는 자산" },
      { value: "none", label: "특별히 없습니다" },
    ],
    mapsTo: [{ doc: "trust", clause: "제8조", label: "처분 금지" }],
  },
  {
    id: "D14",
    track: "estate",
    chapter: "estate",
    section: "내 노후",
    prompt: "상속인들 사이에 다툼이 예상되나요?",
    helper: "예상되는 경우 신탁 구조가 유언보다 분쟁 방지에 유리한 편입니다.",
    type: "choice",
    options: [
      { value: "likely", label: "네, 그럴 것 같습니다" },
      { value: "maybe", label: "가능성은 있습니다" },
      { value: "unlikely", label: "그렇지 않을 것 같습니다" },
    ],
    mapsTo: [{ doc: "trust", clause: "제11조", label: "분쟁 방지 구조" }],
  },
  {
    id: "D15",
    track: "estate",
    chapter: "estate",
    section: "내 노후",
    prompt: "세금 부담에 대해 어떻게 생각하고 계신가요?",
    helper: "NEXT는 세액을 계산하지 않습니다. 다만 어떤 항목을 세무 전문가와 확인해야 하는지 짚어 드립니다.",
    type: "choice",
    options: [
      { value: "minimize", label: "가능한 한 줄이고 싶습니다" },
      { value: "fair", label: "적정하게 내되 분쟁이 없는 게 우선입니다" },
      { value: "unknown", label: "잘 모르겠습니다" },
    ],
    mapsTo: [{ doc: "trust", clause: "부속", label: "세무 검토 항목" }],
  },
  {
    id: "D16",
    track: "estate",
    chapter: "estate",
    section: "내 노후",
    prompt: "가족에게 남기고 싶은 말씀이 있나요?",
    helper: "설계서 서문에 그대로 실립니다.",
    type: "open",
    optional: true,
    placeholder: "예: 집은 어머니가 사시는 동안은 팔지 않았으면 합니다.",
    mapsTo: [{ doc: "trust", clause: "서문", label: "위탁자의 뜻" }],
  },
];
