import type { Question } from "../types";

/**
 * Track B — 미래 판단력 저하 대비
 * 6섹션 22문항. 신탁·후견·지출 설계서 3종을 모두 채운다.
 */
export const futureQuestions: Question[] = [
  /* ── B-1 재산 파악 ─────────────────────────────── */
  {
    id: "B01",
    track: "future",
    section: "재산 파악",
    prompt: "지금 어떤 자산을 가지고 계신가요?",
    helper: "정확한 금액이 아니어도 됩니다. 어떤 자산을 어떤 구조로 보호할지 판단하는 데 씁니다.",
    type: "multi",
    withAmount: true,
    options: [
      { value: "deposit", label: "예금·적금" },
      { value: "invest", label: "주식·펀드·채권" },
      { value: "realestate", label: "부동산" },
      { value: "pension", label: "연금 (국민·퇴직·개인)" },
      { value: "insurance", label: "보험 (해지환급금 있는)" },
      { value: "business", label: "사업체·지분" },
    ],
    mapsTo: [{ doc: "trust", clause: "제2조", label: "신탁재산 후보" }],
  },
  {
    id: "B02",
    track: "future",
    section: "재산 파악",
    prompt: "매달 들어오는 수입은 얼마인가요?",
    helper: "연금·임대소득·근로소득을 합산해 주세요. 자산이 얼마나 버틸지 계산하는 기준이 됩니다.",
    type: "amount",
    min: 0,
    max: 15_000_000,
    step: 100_000,
    presets: [500_000, 1_000_000, 2_000_000, 3_000_000],
    mapsTo: [{ doc: "expense", clause: "§6", label: "지속가능성 추정" }],
  },

  /* ── B-2 신탁 대상과 목적 ──────────────────────── */
  {
    id: "B03",
    track: "future",
    section: "무엇을 묶을까",
    prompt: "이 중 어떤 자산을 미리 묶어두고 싶으세요?",
    helper: "묶어둔 자산은 정해진 목적 외에는 꺼내 쓸 수 없게 됩니다. 신탁재산 목록(제2조)이 됩니다.",
    type: "multi",
    withAmount: true,
    options: [
      { value: "deposit", label: "예금·적금" },
      { value: "invest", label: "주식·펀드" },
      { value: "realestate", label: "부동산" },
      { value: "insurance", label: "보험" },
      { value: "none", label: "아직 정하지 못했어요" },
    ],
    mapsTo: [{ doc: "trust", clause: "제2조", label: "신탁재산" }],
  },
  {
    id: "B04",
    track: "future",
    section: "무엇을 묶을까",
    prompt: "묶어두려는 가장 큰 이유는 무엇인가요?",
    helper: "이 답이 신탁의 목적 조항(제1조)이 되고, 어떤 신탁 유형이 맞는지도 여기서 갈립니다.",
    type: "choice",
    options: [
      { value: "living", label: "내가 판단 못 해도 생활비가 계속 나오게" },
      { value: "medical", label: "치료비·요양비를 확실히 확보하려고" },
      { value: "conflict", label: "가족들이 재산 문제로 다투지 않게" },
      { value: "fraud", label: "사기나 잘못된 판단으로 잃지 않게" },
      { value: "spouse", label: "내가 떠난 뒤 배우자의 생활을 지키려고" },
    ],
    mapsTo: [{ doc: "trust", clause: "제1조", label: "신탁의 목적" }],
  },

  /* ── B-3 발동 조건 ─────────────────────────────── */
  {
    id: "B05",
    track: "future",
    section: "언제 작동할까",
    prompt: "어떤 일이 벌어졌을 때 이 계획이 작동해야 할까요?",
    helper:
      "가장 중요한 조항입니다. 기준이 느슨하면 남용될 수 있고, 너무 엄격하면 정작 필요할 때 작동하지 않습니다.",
    type: "choice",
    options: [
      { value: "doctor1", label: "전문의 진단서 1장", hint: "가장 빠르지만 남용 여지" },
      { value: "doctor2", label: "전문의 2명의 소견이 일치할 때", hint: "실무에서 가장 균형적" },
      { value: "court", label: "가정법원의 후견 심판이 확정될 때", hint: "가장 엄격, 수개월 소요" },
      { value: "designee", label: "내가 지정한 사람의 판단 + 금융기관 확인" },
      { value: "self", label: "내가 미리 요청했을 때만" },
    ],
    mapsTo: [{ doc: "trust", clause: "제4조", label: "지급개시 트리거" }],
  },
  {
    id: "B06",
    track: "future",
    section: "언제 작동할까",
    prompt: "발동 여부를 최종적으로 확인할 사람은 누구인가요?",
    helper: "관리자와 다른 사람이면 좋습니다. 확인하는 사람과 쓰는 사람이 같으면 견제가 없습니다.",
    type: "person",
    mapsTo: [
      { doc: "trust", clause: "제4조", label: "발동 확인자" },
      { doc: "trust", clause: "제9조", label: "신탁감독인 후보" },
    ],
  },

  /* ── B-4 지급 설계 ─────────────────────────────── */
  {
    id: "B07",
    track: "future",
    section: "얼마씩 나올까",
    prompt: "계획이 작동하면, 매달 지급할 생활비는 얼마로 할까요?",
    helper: "지금 쓰는 생활비를 기준으로 잡으세요. 정기지급 조항(제5조)의 기본 금액입니다.",
    type: "amount",
    min: 500_000,
    max: 10_000_000,
    step: 100_000,
    presets: [1_500_000, 2_000_000, 3_000_000, 4_000_000],
    mapsTo: [{ doc: "trust", clause: "제5조", label: "정기지급액" }],
  },
  {
    id: "B08",
    track: "future",
    section: "얼마씩 나올까",
    prompt: "요양시설에 들어가게 되면 월 지급액을 얼마나 올릴까요?",
    helper:
      "요양원 본인부담은 월 100~250만원대가 흔합니다. 증액 트리거를 미리 넣어두면 그때 가족이 다투지 않습니다.",
    type: "amount",
    min: 0,
    max: 5_000_000,
    step: 100_000,
    presets: [1_000_000, 1_500_000, 2_000_000],
    mapsTo: [{ doc: "trust", clause: "제5조", label: "증액 트리거" }],
  },
  {
    id: "B09",
    track: "future",
    section: "얼마씩 나올까",
    prompt: "치료비와 요양비는 어디까지 쓸까요?",
    helper:
      "상한이 없으면 자산이 빠르게 소진되고, 너무 낮으면 정작 치료를 못 받습니다. 수시지급 조항(제6조)입니다.",
    type: "choice",
    options: [
      { value: "unlimited", label: "필요하면 제한 없이" },
      { value: "total_cap", label: "누적 총액 상한을 두고" },
      { value: "yearly_cap", label: "연간 상한을 두고" },
      { value: "family", label: "매번 가족 합의를 거쳐서" },
    ],
    mapsTo: [{ doc: "trust", clause: "제6조", label: "의료비 지급 한도" }],
  },
  {
    id: "B10",
    track: "future",
    section: "얼마씩 나올까",
    prompt: "그 상황에서도 매달 반드시 나가야 하는 지출은 무엇인가요?",
    helper: "자동이체 매트릭스가 됩니다. 여기 없는 항목은 그때 누군가 손으로 처리해야 합니다.",
    type: "multi",
    withAmount: true,
    options: [
      { value: "utility", label: "전기·가스·수도·관리비" },
      { value: "telecom", label: "통신비" },
      { value: "insurance", label: "보험료" },
      { value: "rent", label: "월세·대출 이자" },
      { value: "care", label: "요양·간병비" },
      { value: "hospital", label: "정기 통원 치료비" },
      { value: "support", label: "가족 정기 지원" },
    ],
    mapsTo: [{ doc: "expense", clause: "§2", label: "자동이체 매트릭스" }],
  },

  /* ── B-5 자산 운용과 권한 ──────────────────────── */
  {
    id: "B11",
    track: "future",
    section: "누가 어디까지",
    prompt: "투자자산은 어떻게 관리되길 원하세요?",
    helper: "판단이 어려워진 시점에 급하게 파는 것이 가장 큰 손실 원인입니다. 운용지침(제7조)입니다.",
    type: "choice",
    options: [
      { value: "preserve", label: "그대로 두고 팔지 않기" },
      { value: "phased", label: "생활비가 필요한 만큼만 단계적으로 현금화" },
      { value: "partial", label: "큰돈이 필요할 때만 일부 매도" },
      { value: "delegate", label: "전문가에게 운용을 맡기기" },
    ],
    mapsTo: [{ doc: "trust", clause: "제7조", label: "운용지침" }],
  },
  {
    id: "B12",
    track: "future",
    section: "누가 어디까지",
    prompt: "내 금융을 1차로 관리할 사람은 누구인가요?",
    helper: "신탁의 수익자 대리인이자 후견인 후보가 됩니다.",
    type: "person",
    mapsTo: [
      { doc: "trust", clause: "제3조", label: "1차 관리자" },
      { doc: "guardianship", clause: "§2", label: "후견인 후보" },
    ],
  },
  {
    id: "B13",
    track: "future",
    section: "누가 어디까지",
    prompt: "그분이 먼저 사망하거나 못 하게 되면 다음은 누구인가요?",
    helper: "예비 관리자가 없으면 그 시점에 다시 법원 절차를 밟아야 합니다.",
    type: "person",
    mapsTo: [
      { doc: "trust", clause: "제3조", label: "예비 관리자" },
      { doc: "guardianship", clause: "§2", label: "예비 후견인" },
    ],
  },
  {
    id: "B14",
    track: "future",
    section: "누가 어디까지",
    prompt: "관리자가 혼자 결정해도 되는 금액은 어디까지인가요?",
    helper: "이 금액을 넘으면 공동승인이 필요합니다. 편의와 견제의 경계선입니다.",
    type: "amount",
    min: 100_000,
    max: 50_000_000,
    step: 100_000,
    presets: [500_000, 1_000_000, 3_000_000, 5_000_000],
    mapsTo: [
      { doc: "trust", clause: "제3조", label: "단독 결정 상한" },
      { doc: "expense", clause: "§3", label: "공동승인 기준" },
    ],
  },
  {
    id: "B15",
    track: "future",
    section: "누가 어디까지",
    prompt: "누가 관리하든, 절대 하면 안 되는 일은 무엇인가요?",
    helper: "금지행위 조항(제8조)입니다. 시뮬레이터에서 실제로 이 조항이 거래를 막는 장면을 보게 됩니다.",
    type: "multi",
    options: [
      { value: "sell_estate", label: "부동산 처분" },
      { value: "loan", label: "대출·보증" },
      { value: "gift", label: "제3자에게 증여" },
      { value: "business", label: "사업 투자" },
      { value: "break_deposit", label: "정기예금 중도해지" },
      { value: "cancel_insurance", label: "보험 해지" },
    ],
    mapsTo: [{ doc: "trust", clause: "제8조", label: "금지행위" }],
  },
  {
    id: "B16",
    track: "future",
    section: "누가 어디까지",
    prompt: "그 관리자를 누가 지켜보나요?",
    helper:
      "감독하는 사람이 없는 것이 실무에서 가장 흔한 사고 원인입니다. 신탁감독인·후견감독인에 해당합니다.",
    type: "choice",
    options: [
      { value: "family", label: "다른 가족이 함께 확인" },
      { value: "expert", label: "변호사·법무사 등 전문가" },
      { value: "institution", label: "금융기관이 정기 보고" },
      {
        value: "none",
        label: "따로 두지 않겠습니다",
        warn: "감독자가 없으면 관리자의 판단을 확인할 방법이 없습니다. 실제 분쟁의 상당수가 여기서 시작됩니다.",
      },
    ],
    mapsTo: [
      { doc: "trust", clause: "제9조", label: "신탁감독인" },
      { doc: "guardianship", clause: "§4", label: "후견감독인" },
    ],
  },

  /* ── B-6 신상·종료·귀속 ────────────────────────── */
  {
    id: "B17",
    track: "future",
    section: "몸과 마무리",
    prompt: "요양과 치료 방식에 대해 미리 정해두고 싶은 것이 있나요?",
    helper: "돈만이 아니라 신상에 관한 결정도 후견 사무에 포함됩니다.",
    type: "choice",
    options: [
      { value: "home", label: "가능한 한 집에서 지내고 싶다" },
      { value: "facility", label: "전문 요양시설이 낫다고 본다" },
      { value: "family_decide", label: "그때 가족이 판단하도록" },
      { value: "undecided", label: "아직 생각해 보지 않았다" },
    ],
    mapsTo: [{ doc: "guardianship", clause: "§3", label: "신상보호 선호" }],
  },
  {
    id: "B18",
    track: "future",
    section: "몸과 마무리",
    prompt: "후견인에게 맡길 신상 사무는 어디까지인가요?",
    helper: "고르지 않은 항목은 '제외'로 남고, 그 결정은 그때 아무도 대신할 수 없습니다.",
    type: "multi",
    options: [
      { value: "residence", label: "어디서 살지 결정" },
      { value: "medical", label: "의료행위 동의" },
      { value: "facility", label: "요양시설 입퇴소 계약" },
      { value: "visit", label: "면접교섭 (누가 만날 수 있는지)" },
      { value: "mail", label: "우편·통신물 관리" },
      { value: "eol", label: "연명의료 의사 확인" },
    ],
    mapsTo: [{ doc: "guardianship", clause: "§3", label: "신상보호 사무범위" }],
  },
  {
    id: "B19",
    track: "future",
    section: "몸과 마무리",
    prompt: "제가 건강을 회복하면 이 계획은 어떻게 될까요?",
    helper: "종료 조항이 없으면 회복 후에도 권한이 남아 있게 됩니다.",
    type: "choice",
    options: [
      { value: "auto", label: "자동으로 종료" },
      { value: "request", label: "내가 요청하면 종료" },
      { value: "supervisor", label: "감독인이 확인한 뒤 종료" },
      { value: "court", label: "법원의 종료 심판을 거쳐서" },
    ],
    mapsTo: [{ doc: "trust", clause: "제10조", label: "종료 요건" }],
  },
  {
    id: "B20",
    track: "future",
    section: "몸과 마무리",
    prompt: "이 내용을 나중에 바꾸려면 누구의 동의가 필요할까요?",
    helper: "너무 쉽게 바꿀 수 있으면 계획의 의미가 없고, 너무 어려우면 상황 변화에 대응할 수 없습니다.",
    type: "choice",
    options: [
      { value: "self_only", label: "나 혼자 언제든" },
      { value: "self_supervisor", label: "나 + 감독인 동의" },
      { value: "all", label: "관리자와 감독인 전원 동의" },
      { value: "court", label: "법원의 허가" },
    ],
    mapsTo: [{ doc: "trust", clause: "제10조", label: "변경 요건" }],
  },
  {
    id: "B21",
    track: "future",
    section: "몸과 마무리",
    prompt: "남은 재산은 최종적으로 누구에게 갈까요?",
    helper: "잔여재산 귀속 조항(제11조)입니다. 비워두면 법정상속분에 따르게 됩니다.",
    type: "allocation",
    mapsTo: [{ doc: "trust", clause: "제11조", label: "잔여재산 귀속" }],
  },
  {
    id: "B22",
    track: "future",
    section: "몸과 마무리",
    prompt: "미래의 나와 가족에게 꼭 남기고 싶은 말씀이 있나요?",
    helper: "설계서 서문에 그대로 실립니다. 법적 효력은 없지만 관리자가 판단할 때의 기준이 됩니다.",
    type: "open",
    optional: true,
    placeholder: "예: 집은 팔지 말고, 손주 학비는 도와주었으면 합니다.",
    mapsTo: [{ doc: "trust", clause: "서문", label: "위탁자의 뜻" }],
  },
];
